# coding: utf-8

"""
    Book Management API

    A simple CRUD API for managing a book collection. Built to demonstrate OpenAPI Specification with Flasgger.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@bookapi.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class BooksApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def create_book(self, body, **kwargs):  # noqa: E501
        """Create a new book  # noqa: E501

        Add a new book to the collection.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_book(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param BookInput body: (required)
        :return: Book
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_book_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.create_book_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def create_book_with_http_info(self, body, **kwargs):  # noqa: E501
        """Create a new book  # noqa: E501

        Add a new book to the collection.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_book_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param BookInput body: (required)
        :return: Book
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_book" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `create_book`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/v1/books', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Book',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_book(self, book_id, **kwargs):  # noqa: E501
        """Delete a book  # noqa: E501

        Remove a book from the collection by ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_book(book_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int book_id: The integer ID of the book (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_book_with_http_info(book_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_book_with_http_info(book_id, **kwargs)  # noqa: E501
            return data

    def delete_book_with_http_info(self, book_id, **kwargs):  # noqa: E501
        """Delete a book  # noqa: E501

        Remove a book from the collection by ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_book_with_http_info(book_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int book_id: The integer ID of the book (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['book_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_book" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'book_id' is set
        if ('book_id' not in params or
                params['book_id'] is None):
            raise ValueError("Missing the required parameter `book_id` when calling `delete_book`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'book_id' in params:
            path_params['book_id'] = params['book_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/v1/books/{book_id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_book(self, book_id, **kwargs):  # noqa: E501
        """Get a book by ID  # noqa: E501

        Returns the full details of a single book.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_book(book_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int book_id: The integer ID of the book (required)
        :return: Book
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_book_with_http_info(book_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_book_with_http_info(book_id, **kwargs)  # noqa: E501
            return data

    def get_book_with_http_info(self, book_id, **kwargs):  # noqa: E501
        """Get a book by ID  # noqa: E501

        Returns the full details of a single book.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_book_with_http_info(book_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int book_id: The integer ID of the book (required)
        :return: Book
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['book_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_book" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'book_id' is set
        if ('book_id' not in params or
                params['book_id'] is None):
            raise ValueError("Missing the required parameter `book_id` when calling `get_book`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'book_id' in params:
            path_params['book_id'] = params['book_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/v1/books/{book_id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Book',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def list_books(self, **kwargs):  # noqa: E501
        """List all books  # noqa: E501

        Returns a paginated list of books with optional filtering by genre and keyword search.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_books(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int page: Page number (starts at 1)
        :param int limit: Number of books per page (max 100)
        :param str genre: Filter by genre
        :param str q: Search by title or author
        :return: InlineResponse200
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.list_books_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.list_books_with_http_info(**kwargs)  # noqa: E501
            return data

    def list_books_with_http_info(self, **kwargs):  # noqa: E501
        """List all books  # noqa: E501

        Returns a paginated list of books with optional filtering by genre and keyword search.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_books_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int page: Page number (starts at 1)
        :param int limit: Number of books per page (max 100)
        :param str genre: Filter by genre
        :param str q: Search by title or author
        :return: InlineResponse200
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['page', 'limit', 'genre', 'q']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_books" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'page' in params:
            query_params.append(('page', params['page']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'genre' in params:
            query_params.append(('genre', params['genre']))  # noqa: E501
        if 'q' in params:
            query_params.append(('q', params['q']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/v1/books', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse200',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_book(self, body, book_id, **kwargs):  # noqa: E501
        """Update a book  # noqa: E501

        Fully replace the data of an existing book.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_book(body, book_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param BookInput body: (required)
        :param int book_id: The integer ID of the book (required)
        :return: Book
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_book_with_http_info(body, book_id, **kwargs)  # noqa: E501
        else:
            (data) = self.update_book_with_http_info(body, book_id, **kwargs)  # noqa: E501
            return data

    def update_book_with_http_info(self, body, book_id, **kwargs):  # noqa: E501
        """Update a book  # noqa: E501

        Fully replace the data of an existing book.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_book_with_http_info(body, book_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param BookInput body: (required)
        :param int book_id: The integer ID of the book (required)
        :return: Book
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'book_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_book" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `update_book`")  # noqa: E501
        # verify the required parameter 'book_id' is set
        if ('book_id' not in params or
                params['book_id'] is None):
            raise ValueError("Missing the required parameter `book_id` when calling `update_book`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'book_id' in params:
            path_params['book_id'] = params['book_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/v1/books/{book_id}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Book',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
