# coding: utf-8

# flake8: noqa
"""
    Book Management API

    A simple CRUD API for managing a book collection. Built to demonstrate OpenAPI Specification with Flasgger.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@bookapi.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.book import Book
from swagger_client.models.book_input import BookInput
from swagger_client.models.error import Error
from swagger_client.models.inline_response200 import InlineResponse200
from swagger_client.models.pagination import Pagination
