# coding: utf-8

"""
    Book Management API

    A simple CRUD API for managing a book collection. Built to demonstrate OpenAPI Specification with Flasgger.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@bookapi.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BookInput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'title': 'str',
        'author': 'str',
        'isbn': 'str',
        'genre': 'str',
        'published_year': 'int',
        'price': 'float'
    }

    attribute_map = {
        'title': 'title',
        'author': 'author',
        'isbn': 'isbn',
        'genre': 'genre',
        'published_year': 'publishedYear',
        'price': 'price'
    }

    def __init__(self, title=None, author=None, isbn=None, genre=None, published_year=None, price=None):  # noqa: E501
        """BookInput - a model defined in Swagger"""  # noqa: E501
        self._title = None
        self._author = None
        self._isbn = None
        self._genre = None
        self._published_year = None
        self._price = None
        self.discriminator = None
        self.title = title
        self.author = author
        if isbn is not None:
            self.isbn = isbn
        self.genre = genre
        if published_year is not None:
            self.published_year = published_year
        if price is not None:
            self.price = price

    @property
    def title(self):
        """Gets the title of this BookInput.  # noqa: E501


        :return: The title of this BookInput.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this BookInput.


        :param title: The title of this BookInput.  # noqa: E501
        :type: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def author(self):
        """Gets the author of this BookInput.  # noqa: E501


        :return: The author of this BookInput.  # noqa: E501
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author):
        """Sets the author of this BookInput.


        :param author: The author of this BookInput.  # noqa: E501
        :type: str
        """
        if author is None:
            raise ValueError("Invalid value for `author`, must not be `None`")  # noqa: E501

        self._author = author

    @property
    def isbn(self):
        """Gets the isbn of this BookInput.  # noqa: E501


        :return: The isbn of this BookInput.  # noqa: E501
        :rtype: str
        """
        return self._isbn

    @isbn.setter
    def isbn(self, isbn):
        """Sets the isbn of this BookInput.


        :param isbn: The isbn of this BookInput.  # noqa: E501
        :type: str
        """

        self._isbn = isbn

    @property
    def genre(self):
        """Gets the genre of this BookInput.  # noqa: E501


        :return: The genre of this BookInput.  # noqa: E501
        :rtype: str
        """
        return self._genre

    @genre.setter
    def genre(self, genre):
        """Sets the genre of this BookInput.


        :param genre: The genre of this BookInput.  # noqa: E501
        :type: str
        """
        if genre is None:
            raise ValueError("Invalid value for `genre`, must not be `None`")  # noqa: E501
        allowed_values = ["fiction", "non-fiction", "sci-fi", "history", "biography"]  # noqa: E501
        if genre not in allowed_values:
            raise ValueError(
                "Invalid value for `genre` ({0}), must be one of {1}"  # noqa: E501
                .format(genre, allowed_values)
            )

        self._genre = genre

    @property
    def published_year(self):
        """Gets the published_year of this BookInput.  # noqa: E501


        :return: The published_year of this BookInput.  # noqa: E501
        :rtype: int
        """
        return self._published_year

    @published_year.setter
    def published_year(self, published_year):
        """Sets the published_year of this BookInput.


        :param published_year: The published_year of this BookInput.  # noqa: E501
        :type: int
        """

        self._published_year = published_year

    @property
    def price(self):
        """Gets the price of this BookInput.  # noqa: E501


        :return: The price of this BookInput.  # noqa: E501
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this BookInput.


        :param price: The price of this BookInput.  # noqa: E501
        :type: float
        """

        self._price = price

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BookInput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BookInput):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
