from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ApiError(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code=None, message=None):  # noqa: E501
        """ApiError - a model defined in OpenAPI

        :param code: The code of this ApiError.  # noqa: E501
        :type code: str
        :param message: The message of this ApiError.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'code': str,
            'message': str
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message'
        }

        self._code = code
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ApiError':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApiError of this ApiError.  # noqa: E501
        :rtype: ApiError
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> str:
        """Gets the code of this ApiError.

        Mã lỗi định danh. Các giá trị có thể: - INVALID_PARAM: query param sai - BAD_REQUEST: body không phải JSON - BOOK_NOT_FOUND: không tìm thấy sách - NOT_FOUND: route không tồn tại - METHOD_NOT_ALLOWED: method không hỗ trợ - INTERNAL_ERROR: lỗi server  # noqa: E501

        :return: The code of this ApiError.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this ApiError.

        Mã lỗi định danh. Các giá trị có thể: - INVALID_PARAM: query param sai - BAD_REQUEST: body không phải JSON - BOOK_NOT_FOUND: không tìm thấy sách - NOT_FOUND: route không tồn tại - METHOD_NOT_ALLOWED: method không hỗ trợ - INTERNAL_ERROR: lỗi server  # noqa: E501

        :param code: The code of this ApiError.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this ApiError.

        Mô tả lỗi. Có thể là string rỗng với lỗi từ errorhandler.  # noqa: E501

        :return: The message of this ApiError.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ApiError.

        Mô tả lỗi. Có thể là string rỗng với lỗi từ errorhandler.  # noqa: E501

        :param message: The message of this ApiError.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message
