from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.book import Book
from openapi_server.models.pagination import Pagination
from openapi_server import util

from openapi_server.models.book import Book  # noqa: E501
from openapi_server.models.pagination import Pagination  # noqa: E501

class BookListResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None, pagination=None):  # noqa: E501
        """BookListResponse - a model defined in OpenAPI

        :param data: The data of this BookListResponse.  # noqa: E501
        :type data: List[Book]
        :param pagination: The pagination of this BookListResponse.  # noqa: E501
        :type pagination: Pagination
        """
        self.openapi_types = {
            'data': List[Book],
            'pagination': Pagination
        }

        self.attribute_map = {
            'data': 'data',
            'pagination': 'pagination'
        }

        self._data = data
        self._pagination = pagination

    @classmethod
    def from_dict(cls, dikt) -> 'BookListResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BookListResponse of this BookListResponse.  # noqa: E501
        :rtype: BookListResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[Book]:
        """Gets the data of this BookListResponse.


        :return: The data of this BookListResponse.
        :rtype: List[Book]
        """
        return self._data

    @data.setter
    def data(self, data: List[Book]):
        """Sets the data of this BookListResponse.


        :param data: The data of this BookListResponse.
        :type data: List[Book]
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data

    @property
    def pagination(self) -> Pagination:
        """Gets the pagination of this BookListResponse.


        :return: The pagination of this BookListResponse.
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination: Pagination):
        """Sets the pagination of this BookListResponse.


        :param pagination: The pagination of this BookListResponse.
        :type pagination: Pagination
        """
        if pagination is None:
            raise ValueError("Invalid value for `pagination`, must not be `None`")  # noqa: E501

        self._pagination = pagination
