from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Genre(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    FICTION = 'fiction'
    NON_MINUS_FICTION = 'non-fiction'
    SCI_MINUS_FI = 'sci-fi'
    HISTORY = 'history'
    BIOGRAPHY = 'biography'
    def __init__(self):  # noqa: E501
        """Genre - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Genre':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Genre of this Genre.  # noqa: E501
        :rtype: Genre
        """
        return util.deserialize_model(dikt, cls)
