from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Pagination(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, page=None, limit=None, total=None, total_pages=None):  # noqa: E501
        """Pagination - a model defined in OpenAPI

        :param page: The page of this Pagination.  # noqa: E501
        :type page: int
        :param limit: The limit of this Pagination.  # noqa: E501
        :type limit: int
        :param total: The total of this Pagination.  # noqa: E501
        :type total: int
        :param total_pages: The total_pages of this Pagination.  # noqa: E501
        :type total_pages: int
        """
        self.openapi_types = {
            'page': int,
            'limit': int,
            'total': int,
            'total_pages': int
        }

        self.attribute_map = {
            'page': 'page',
            'limit': 'limit',
            'total': 'total',
            'total_pages': 'totalPages'
        }

        self._page = page
        self._limit = limit
        self._total = total
        self._total_pages = total_pages

    @classmethod
    def from_dict(cls, dikt) -> 'Pagination':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Pagination of this Pagination.  # noqa: E501
        :rtype: Pagination
        """
        return util.deserialize_model(dikt, cls)

    @property
    def page(self) -> int:
        """Gets the page of this Pagination.

        Trang hiện tại (input page sau khi clamp: max(1, page)).  # noqa: E501

        :return: The page of this Pagination.
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page: int):
        """Sets the page of this Pagination.

        Trang hiện tại (input page sau khi clamp: max(1, page)).  # noqa: E501

        :param page: The page of this Pagination.
        :type page: int
        """
        if page is None:
            raise ValueError("Invalid value for `page`, must not be `None`")  # noqa: E501

        self._page = page

    @property
    def limit(self) -> int:
        """Gets the limit of this Pagination.

        Số bản ghi/trang (input limit sau khi clamp vào [1, 100]).  # noqa: E501

        :return: The limit of this Pagination.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit: int):
        """Sets the limit of this Pagination.

        Số bản ghi/trang (input limit sau khi clamp vào [1, 100]).  # noqa: E501

        :param limit: The limit of this Pagination.
        :type limit: int
        """
        if limit is None:
            raise ValueError("Invalid value for `limit`, must not be `None`")  # noqa: E501

        self._limit = limit

    @property
    def total(self) -> int:
        """Gets the total of this Pagination.

        Tổng số sách sau khi áp dụng filter genre và q.  # noqa: E501

        :return: The total of this Pagination.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this Pagination.

        Tổng số sách sau khi áp dụng filter genre và q.  # noqa: E501

        :param total: The total of this Pagination.
        :type total: int
        """
        if total is None:
            raise ValueError("Invalid value for `total`, must not be `None`")  # noqa: E501

        self._total = total

    @property
    def total_pages(self) -> int:
        """Gets the total_pages of this Pagination.

        max(1, ceil(total / limit))  # noqa: E501

        :return: The total_pages of this Pagination.
        :rtype: int
        """
        return self._total_pages

    @total_pages.setter
    def total_pages(self, total_pages: int):
        """Sets the total_pages of this Pagination.

        max(1, ceil(total / limit))  # noqa: E501

        :param total_pages: The total_pages of this Pagination.
        :type total_pages: int
        """
        if total_pages is None:
            raise ValueError("Invalid value for `total_pages`, must not be `None`")  # noqa: E501

        self._total_pages = total_pages
