from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class CPNhTSCh400Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code=None, message=None):  # noqa: E501
        """CPNhTSCh400Response - a model defined in OpenAPI

        :param code: The code of this CPNhTSCh400Response.  # noqa: E501
        :type code: str
        :param message: The message of this CPNhTSCh400Response.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'code': str,
            'message': str
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message'
        }

        self._code = code
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'CPNhTSCh400Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The C_p_nh_t_s_ch_400_response of this CPNhTSCh400Response.  # noqa: E501
        :rtype: CPNhTSCh400Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> str:
        """Gets the code of this CPNhTSCh400Response.


        :return: The code of this CPNhTSCh400Response.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this CPNhTSCh400Response.


        :param code: The code of this CPNhTSCh400Response.
        :type code: str
        """

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this CPNhTSCh400Response.


        :return: The message of this CPNhTSCh400Response.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this CPNhTSCh400Response.


        :param message: The message of this CPNhTSCh400Response.
        :type message: str
        """

        self._message = message
