from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class CPNhTSChRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, title=None, author=None, genre=None, published_year=None, price=None):  # noqa: E501
        """CPNhTSChRequest - a model defined in OpenAPI

        :param title: The title of this CPNhTSChRequest.  # noqa: E501
        :type title: str
        :param author: The author of this CPNhTSChRequest.  # noqa: E501
        :type author: str
        :param genre: The genre of this CPNhTSChRequest.  # noqa: E501
        :type genre: str
        :param published_year: The published_year of this CPNhTSChRequest.  # noqa: E501
        :type published_year: float
        :param price: The price of this CPNhTSChRequest.  # noqa: E501
        :type price: float
        """
        self.openapi_types = {
            'title': str,
            'author': str,
            'genre': str,
            'published_year': float,
            'price': float
        }

        self.attribute_map = {
            'title': 'title',
            'author': 'author',
            'genre': 'genre',
            'published_year': 'publishedYear',
            'price': 'price'
        }

        self._title = title
        self._author = author
        self._genre = genre
        self._published_year = published_year
        self._price = price

    @classmethod
    def from_dict(cls, dikt) -> 'CPNhTSChRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The C_p_nh_t_s_ch_request of this CPNhTSChRequest.  # noqa: E501
        :rtype: CPNhTSChRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this CPNhTSChRequest.


        :return: The title of this CPNhTSChRequest.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this CPNhTSChRequest.


        :param title: The title of this CPNhTSChRequest.
        :type title: str
        """

        self._title = title

    @property
    def author(self) -> str:
        """Gets the author of this CPNhTSChRequest.


        :return: The author of this CPNhTSChRequest.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this CPNhTSChRequest.


        :param author: The author of this CPNhTSChRequest.
        :type author: str
        """

        self._author = author

    @property
    def genre(self) -> str:
        """Gets the genre of this CPNhTSChRequest.


        :return: The genre of this CPNhTSChRequest.
        :rtype: str
        """
        return self._genre

    @genre.setter
    def genre(self, genre: str):
        """Sets the genre of this CPNhTSChRequest.


        :param genre: The genre of this CPNhTSChRequest.
        :type genre: str
        """

        self._genre = genre

    @property
    def published_year(self) -> float:
        """Gets the published_year of this CPNhTSChRequest.


        :return: The published_year of this CPNhTSChRequest.
        :rtype: float
        """
        return self._published_year

    @published_year.setter
    def published_year(self, published_year: float):
        """Sets the published_year of this CPNhTSChRequest.


        :param published_year: The published_year of this CPNhTSChRequest.
        :type published_year: float
        """

        self._published_year = published_year

    @property
    def price(self) -> float:
        """Gets the price of this CPNhTSChRequest.


        :return: The price of this CPNhTSChRequest.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this CPNhTSChRequest.


        :param price: The price of this CPNhTSChRequest.
        :type price: float
        """

        self._price = price
