from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.ly_danh_sch_sch200_response_data_inner import LYDanhSChSCh200ResponseDataInner
from openapi_server.models.ly_danh_sch_sch200_response_pagination import LYDanhSChSCh200ResponsePagination
from openapi_server import util

from openapi_server.models.ly_danh_sch_sch200_response_data_inner import LYDanhSChSCh200ResponseDataInner  # noqa: E501
from openapi_server.models.ly_danh_sch_sch200_response_pagination import LYDanhSChSCh200ResponsePagination  # noqa: E501

class LYDanhSChSCh200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None, pagination=None):  # noqa: E501
        """LYDanhSChSCh200Response - a model defined in OpenAPI

        :param data: The data of this LYDanhSChSCh200Response.  # noqa: E501
        :type data: List[LYDanhSChSCh200ResponseDataInner]
        :param pagination: The pagination of this LYDanhSChSCh200Response.  # noqa: E501
        :type pagination: LYDanhSChSCh200ResponsePagination
        """
        self.openapi_types = {
            'data': List[LYDanhSChSCh200ResponseDataInner],
            'pagination': LYDanhSChSCh200ResponsePagination
        }

        self.attribute_map = {
            'data': 'data',
            'pagination': 'pagination'
        }

        self._data = data
        self._pagination = pagination

    @classmethod
    def from_dict(cls, dikt) -> 'LYDanhSChSCh200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The L_y_danh_s_ch_s_ch_200_response of this LYDanhSChSCh200Response.  # noqa: E501
        :rtype: LYDanhSChSCh200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[LYDanhSChSCh200ResponseDataInner]:
        """Gets the data of this LYDanhSChSCh200Response.


        :return: The data of this LYDanhSChSCh200Response.
        :rtype: List[LYDanhSChSCh200ResponseDataInner]
        """
        return self._data

    @data.setter
    def data(self, data: List[LYDanhSChSCh200ResponseDataInner]):
        """Sets the data of this LYDanhSChSCh200Response.


        :param data: The data of this LYDanhSChSCh200Response.
        :type data: List[LYDanhSChSCh200ResponseDataInner]
        """

        self._data = data

    @property
    def pagination(self) -> LYDanhSChSCh200ResponsePagination:
        """Gets the pagination of this LYDanhSChSCh200Response.


        :return: The pagination of this LYDanhSChSCh200Response.
        :rtype: LYDanhSChSCh200ResponsePagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination: LYDanhSChSCh200ResponsePagination):
        """Sets the pagination of this LYDanhSChSCh200Response.


        :param pagination: The pagination of this LYDanhSChSCh200Response.
        :type pagination: LYDanhSChSCh200ResponsePagination
        """

        self._pagination = pagination
