from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class LYDanhSChSCh200ResponsePagination(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, page=None, limit=None, total=None, total_pages=None):  # noqa: E501
        """LYDanhSChSCh200ResponsePagination - a model defined in OpenAPI

        :param page: The page of this LYDanhSChSCh200ResponsePagination.  # noqa: E501
        :type page: float
        :param limit: The limit of this LYDanhSChSCh200ResponsePagination.  # noqa: E501
        :type limit: float
        :param total: The total of this LYDanhSChSCh200ResponsePagination.  # noqa: E501
        :type total: float
        :param total_pages: The total_pages of this LYDanhSChSCh200ResponsePagination.  # noqa: E501
        :type total_pages: float
        """
        self.openapi_types = {
            'page': float,
            'limit': float,
            'total': float,
            'total_pages': float
        }

        self.attribute_map = {
            'page': 'page',
            'limit': 'limit',
            'total': 'total',
            'total_pages': 'totalPages'
        }

        self._page = page
        self._limit = limit
        self._total = total
        self._total_pages = total_pages

    @classmethod
    def from_dict(cls, dikt) -> 'LYDanhSChSCh200ResponsePagination':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The L_y_danh_s_ch_s_ch_200_response_pagination of this LYDanhSChSCh200ResponsePagination.  # noqa: E501
        :rtype: LYDanhSChSCh200ResponsePagination
        """
        return util.deserialize_model(dikt, cls)

    @property
    def page(self) -> float:
        """Gets the page of this LYDanhSChSCh200ResponsePagination.


        :return: The page of this LYDanhSChSCh200ResponsePagination.
        :rtype: float
        """
        return self._page

    @page.setter
    def page(self, page: float):
        """Sets the page of this LYDanhSChSCh200ResponsePagination.


        :param page: The page of this LYDanhSChSCh200ResponsePagination.
        :type page: float
        """

        self._page = page

    @property
    def limit(self) -> float:
        """Gets the limit of this LYDanhSChSCh200ResponsePagination.


        :return: The limit of this LYDanhSChSCh200ResponsePagination.
        :rtype: float
        """
        return self._limit

    @limit.setter
    def limit(self, limit: float):
        """Sets the limit of this LYDanhSChSCh200ResponsePagination.


        :param limit: The limit of this LYDanhSChSCh200ResponsePagination.
        :type limit: float
        """

        self._limit = limit

    @property
    def total(self) -> float:
        """Gets the total of this LYDanhSChSCh200ResponsePagination.


        :return: The total of this LYDanhSChSCh200ResponsePagination.
        :rtype: float
        """
        return self._total

    @total.setter
    def total(self, total: float):
        """Sets the total of this LYDanhSChSCh200ResponsePagination.


        :param total: The total of this LYDanhSChSCh200ResponsePagination.
        :type total: float
        """

        self._total = total

    @property
    def total_pages(self) -> float:
        """Gets the total_pages of this LYDanhSChSCh200ResponsePagination.


        :return: The total_pages of this LYDanhSChSCh200ResponsePagination.
        :rtype: float
        """
        return self._total_pages

    @total_pages.setter
    def total_pages(self, total_pages: float):
        """Sets the total_pages of this LYDanhSChSCh200ResponsePagination.


        :param total_pages: The total_pages of this LYDanhSChSCh200ResponsePagination.
        :type total_pages: float
        """

        self._total_pages = total_pages
