from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Ping200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, msg=None):  # noqa: E501
        """Ping200Response - a model defined in OpenAPI

        :param msg: The msg of this Ping200Response.  # noqa: E501
        :type msg: str
        """
        self.openapi_types = {
            'msg': str
        }

        self.attribute_map = {
            'msg': 'msg'
        }

        self._msg = msg

    @classmethod
    def from_dict(cls, dikt) -> 'Ping200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Ping_200_response of this Ping200Response.  # noqa: E501
        :rtype: Ping200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def msg(self) -> str:
        """Gets the msg of this Ping200Response.


        :return: The msg of this Ping200Response.
        :rtype: str
        """
        return self._msg

    @msg.setter
    def msg(self, msg: str):
        """Sets the msg of this Ping200Response.


        :param msg: The msg of this Ping200Response.
        :type msg: str
        """

        self._msg = msg
