# coding: utf-8

"""
    Book Management API

    A simple CRUD API for managing a book collection. Built to demonstrate OpenAPI Specification with Flasgger.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@bookapi.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.books_api import BooksApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBooksApi(unittest.TestCase):
    """BooksApi unit test stubs"""

    def setUp(self):
        self.api = BooksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_book(self):
        """Test case for create_book

        Create a new book  # noqa: E501
        """
        pass

    def test_delete_book(self):
        """Test case for delete_book

        Delete a book  # noqa: E501
        """
        pass

    def test_get_book(self):
        """Test case for get_book

        Get a book by ID  # noqa: E501
        """
        pass

    def test_list_books(self):
        """Test case for list_books

        List all books  # noqa: E501
        """
        pass

    def test_update_book(self):
        """Test case for update_book

        Update a book  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
