# coding: utf-8

"""
    Book Management API

    A simple CRUD API for managing a book collection. Built to demonstrate OpenAPI Specification with Flasgger.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@bookapi.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.book_input import BookInput  # noqa: E501
from swagger_client.rest import ApiException


class TestBookInput(unittest.TestCase):
    """BookInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBookInput(self):
        """Test BookInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.book_input.BookInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
